# These settings can be accessed via {{ site.title }}, {{ site.email }}, in the html pages.
title: Bianca Maria Art
email: # Add email if known, leaving blank for now
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Bianca Maria.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biancamaria.art" # the base hostname & protocol for your site
github_username: biancamaria-art
repository: biancamaria-art/biancamaria-art.github.io

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

  - index.html

# Local development settings
port: 4200
